### ISSUE TITLE
where to buy  some wrist logging able device like e4-wristband

### ISSUE THREAD

**Issue by Sandy4321** [ChildMindInstitute/HBN-wearable-analysis#9]
great code and paper
https://www.biorxiv.org/content/10.1101/183772v1.full.pdf

only can you share where to buy 
some wrist logging able device like e4-wristband
https://store.empatica.com/products/e4-wristband?variant=17719039950953

but for reasonable price ?

**Comment by shnizzedy** [comment]
Hi @Sandy4321,

The E4 is a clinical-research-grade device. The link you provided above is the only place I know of to order one.

Empatica [say](https://support.empatica.com/hc/en-us/articles/203934675-Is-the-E4-suitable-for-personal-use-)
> The Empatica E4 is designed for use by researchers in clinical research studies with software that offers access to raw data. The data are difficult to interpret without 3rd party software or extensive technical expertise.
>
> For personal use, we recommend using the Embrace watch, not the E4 wristband. 

If you do want one or more E4s for research, [they do have an academic discount](https://support.empatica.com/hc/en-us/articles/360035568032-How-to-purchase-E4):
> Note: We offer an academic discount of 18% for all university purchases. Just email support@empatica.com to request the discount code to be used at checkout.

Otherwise, because wearable tracking devices is a fast-moving market, I'd suggest making a list of features you want and seeing what's currently available. Our analysis was in service of a one-time bulk purchase 4 years ago; I'm sure that most to all of the consumer-grade devices we looked at have been replaced by newer models or otherwise discontinued by now.
